# Generated by Django 2.1.3 on 2018-11-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='capa',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
